# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: $(Year:yy).$(Month).$(DayOfMonth).$(BuildID)

trigger:
- main 
- feature/*

pool:
  vmImage: 'windows-latest'

variables:
  build.name: 'Wrak.ListComponentRoutes'
  build.configuration: 'Release'
  build.project: $(build.name).sln
  projects: '**/*.csproj'
  dotNetCoreSDK: 5.0.x

steps:
- task: UseDotNet@2
  displayName: 'Use .Net 5 SDK'
  inputs:
    packageType: sdk
    version: $(dotNetCoreSDK)

- task: DotNetCoreCLI@2 
  displayName: 'DotNet Restore From Feeds' 
  inputs: 
    command: restore 
    projects: '$(projects)' 
    feedsToUse: 'select'    
    versioningScheme: byBuildNumber

- task: DotNetCoreCLI@2
  displayName: 'Dotnet Build $(build.configuration)'
  inputs:
    command: 'build'
    projects: $(build.project)
    arguments: '--configuration $(build.configuration) /p:SourceRevisionId=$(Build.SourceVersion)'

- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'

- task: DotNetCoreCLI@2
  displayName: 'Dotnet Publish'
  inputs:
    command: 'publish'
    projects: $(build.project)
    publishWebProjects: false
    zipAfterPublish: false    
    modifyOutputPath: false
    arguments: '--configuration $(build.configuration) /p:PublishDir=artifacts'

- task: NuGetCommand@2
  displayName: 'Package'
  inputs:
    command: pack
    packagesToPack: '**/Wrak.ListComponentRoutes.csproj'
    packDestination: '$(Build.ArtifactStagingDirectory)'

- task: NuGetAuthenticate@0
  displayName: 'Authenticate with NuGet'
  inputs:
    nuGetServiceConnections: 'wrakocy.nuget'

- task: NuGetCommand@2
  displayName: 'Push Package to NuGet Feed'
  inputs:
    command: push
    nuGetFeedType: external
    versioningScheme: byBuildNumber
    versionEnvVar: $(build.buildnumber)
